from services.groq_client import client

def generate_revision_notes(topic, view_mode):
    """
    This function generates revision notes for a given topic and view mode (Quick Summary or Detailed Notes).
    
    Args:
    topic (str): The topic for the revision notes.
    view_mode (str): The view mode - "Quick Summary" or "Detailed Notes".
    
    Returns:
    str: The generated revision notes content.
    """
    
    if view_mode == "Quick Summary":
        prompt = f"Provide a quick summary of {topic} for revision purposes."
    else:
        prompt = f"Provide detailed revision notes for {topic}."

    # Send the request to Groq API to generate the notes
    response = client.chat.completions.create(
        model="meta-llama/llama-4-scout-17b-16e-instruct",  # Replace with your model ID
        messages=[
            {"role": "system", "content": "Generate revision notes."},
            {"role": "user", "content": prompt}
        ]
    )
    
    # Return the revision notes generated by Groq
    return response.choices[0].message.content
